api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "ASPNetCore Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "8df52beaa83510545f5598f58312bbcf65eea24055c2bef000419caa10fe3534"
    source = "https://download.visualstudio.microsoft.com/download/pr/5e23ff62-5ddd-4fc5-9f72-e4250110cf58/956138123fcefedca324b0fea6c23d15/aspnetcore-runtime-2.1.18-linux-x64.tar.gz"
    source_sha256 = "8f3a6092b26dae5c27318975c4d89297d64425424809a6c36c984f02723475a1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.18_linux_x64_any-stack_8df52bea.tar.xz"
    version = "2.1.18"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "88b4f28b3df8d954d5e06c94e8eb345f0e8dbfe77bd56a5c9c8cb350e065e71a"
    source = "https://download.visualstudio.microsoft.com/download/pr/abf8cad9-fe36-4bb6-9cdb-926a50bf63c6/5dc2f4e3e133ef073f12340d4fd6e943/aspnetcore-runtime-2.1.19-linux-x64.tar.gz"
    source_sha256 = "ee93178335ab356a289c25c411354bef70b5a5bdcb9462c419011210e391e8f3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.19_linux_x64_any-stack_88b4f28b.tar.xz"
    version = "2.1.19"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "078c4833881fc72490a11571c564f40f5a6516256965d312d86b57cc9f8560b0"
    source = "https://download.visualstudio.microsoft.com/download/pr/6827d794-a218-4352-b3b3-a19ec773c975/e3e53bc2f20df220a29c6e09f74d8a00/aspnetcore-runtime-3.1.5-linux-x64.tar.gz"
    source_sha256 = "bf202e612374eecf089b08db2085f36e54c09d6e93db0ff4244580ee47b9c61f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.5_linux_x64_any-stack_078c4833.tar.xz"
    version = "3.1.5"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "36244a15a4eadfe9d03299a79f3abc2d85a483f17dc8f8bcecd9b273d06c143d"
    source = "https://download.visualstudio.microsoft.com/download/pr/9eadec7a-dd7e-476d-a348-c4bf946a0bad/c11b5123931ee17faba27e5debe74731/aspnetcore-runtime-3.1.6-linux-x64.tar.gz"
    source_sha256 = "70734b39eddea268a16459a5178a4fe727af3051e8a0f78880906ff109f9f8d3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.6_linux_x64_any-stack_36244a15.tar.xz"
    version = "3.1.6"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
