api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.Net Core Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "66e1b0f28c3603ae4ac1f120da0b23f40947e08eb7ed8e898549c1b2f4216a73"
    source = "https://download.visualstudio.microsoft.com/download/pr/c1798274-4f4e-4e5b-8337-cb477add793c/2ab1c7f92fe497e07304b0b25c5f7845/aspnetcore-runtime-2.1.22-linux-x64.tar.gz"
    source_sha256 = "053cb445608296a5c6d988980bdbfe1ee36602d1445fd67835d29eceab916ef0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.22_linux_x64_any-stack_66e1b0f2.tar.xz"
    version = "2.1.22"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "b94ea8672b944f550602d127a9369831d617d38a54e3c4db8e1a9523190f0657"
    source = "https://download.visualstudio.microsoft.com/download/pr/3422a123-3f37-4544-b0ed-e3922b50e1b0/c34c607ba18a67763bacded434607c56/aspnetcore-runtime-2.1.23-linux-x64.tar.gz"
    source_sha256 = "d13d536693c2d40c1237e1831c302271a497ea1576f8a1aae5676f6442e9a6b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.23_linux_x64_any-stack_b94ea867.tar.xz"
    version = "2.1.23"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "266c2cffb5263bfcb3ef6d5e25c2fe5e2969fe219958ef7a885e7b8c4abdddcd"
    source = "https://download.visualstudio.microsoft.com/download/pr/eca743d3-030f-4b1b-bd15-3573091f1c02/f3e464abc31deb7bc2747ed6cc1a8f5c/aspnetcore-runtime-3.1.10-linux-x64.tar.gz"
    source_sha256 = "b58376e76c68f03e142ac9a771b782cb7be926a16e920d83c711903b82608f3a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.10_linux_x64_any-stack_266c2cff.tar.xz"
    version = "3.1.10"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "e14a49fdba8492230794860e5276c2d6405a1548832565785fad5d764317531c"
    source = "https://download.visualstudio.microsoft.com/download/pr/91e7ea86-985e-401f-b3ed-103fb0fe6058/c1b1f633c9465c630e828f7f8bdf8f4e/aspnetcore-runtime-3.1.11-linux-x64.tar.gz"
    source_sha256 = "628dffa95fd8a4ac1a3f13457196b7721873288ed673c085da55daa2fb45e828"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.11_linux_x64_any-stack_e14a49fd.tar.xz"
    version = "3.1.11"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "901daa2c6f528b7d355064aaab3bd98fc1e63e134ae43d72cecd72c55325ce5a"
    source = "https://download.visualstudio.microsoft.com/download/pr/ff9a5b2e-704b-4ff2-bf2f-4bac619915af/e771f72b10ad5160ab5f3d70c287e948/aspnetcore-runtime-5.0.0-linux-x64.tar.gz"
    source_sha256 = "de6ab398bd0c7757c505a25d6eaf560d8f4b3c3a66b0462d6e8afff97ac5e2d1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.0_linux_x64_any-stack_901daa2c.tar.xz"
    version = "5.0.0"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "eab1acb0f7cc5c8354db6a380090707a1797df428f1628fe314fc1efc1c06d37"
    source = "https://download.visualstudio.microsoft.com/download/pr/6bea1cea-89e8-4bf7-9fc1-f77380443db1/0fb741b7d587cce798ebee80732196ef/aspnetcore-runtime-5.0.1-linux-x64.tar.gz"
    source_sha256 = "0e0b71ca2a171dd24fe16c1c68f08a30f644790792f277f9b40a084c18aa5726"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.1_linux_x64_any-stack_eab1acb0.tar.xz"
    version = "5.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
