api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "8082787c5ccaea684953e7b7b7435b86a03a143609164c52b9dbf1cb772ea35c"
    source = "https://download.visualstudio.microsoft.com/download/pr/3b8d8ee1-0670-46d5-ae77-e824e716993e/cb4a0f5d98ff86578ee0cb95f6e34c8f/aspnetcore-runtime-2.1.25-linux-x64.tar.gz"
    source_sha256 = "04823ee559119e502d30f0a005aa7c1846136c0b64898bfe90adebb695a38c7f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.25_linux_x64_any-stack_8082787c.tar.xz"
    version = "2.1.25"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "6ff9d97f61bb6f50964734851efb0b74301a31dc68e46e77498328e1b80c2503"
    source = "https://download.visualstudio.microsoft.com/download/pr/29ba76e1-db96-4cbb-8964-0a6c859712c4/d6e56c1dacf78b6846464a77dda4115d/aspnetcore-runtime-2.1.26-linux-x64.tar.gz"
    source_sha256 = "72e08cd2a26d2ce26bb0c61390feaf0781fadf60fa70d9edf56a2049b0f1e77d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.26_linux_x64_any-stack_6ff9d97f.tar.xz"
    version = "2.1.26"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "e14a49fdba8492230794860e5276c2d6405a1548832565785fad5d764317531c"
    source = "https://download.visualstudio.microsoft.com/download/pr/91e7ea86-985e-401f-b3ed-103fb0fe6058/c1b1f633c9465c630e828f7f8bdf8f4e/aspnetcore-runtime-3.1.11-linux-x64.tar.gz"
    source_sha256 = "628dffa95fd8a4ac1a3f13457196b7721873288ed673c085da55daa2fb45e828"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.11_linux_x64_any-stack_e14a49fd.tar.xz"
    version = "3.1.11"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "90d8e6ebfccc089670a58d53399740c4d409cb31ef187b53884a376a98f215c5"
    source = "https://download.visualstudio.microsoft.com/download/pr/c5d69db1-7735-4473-973c-220b56c32e3d/8b907777706429063b0ed646a5445cdf/aspnetcore-runtime-3.1.12-linux-x64.tar.gz"
    source_sha256 = "a081997862e3dcac9769d0660ba6e86cb23bf6e36e80fc70050854570ed48d00"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.12_linux_x64_any-stack_90d8e6eb.tar.xz"
    version = "3.1.12"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "d94d4349407cec87de9b6044f7f13d71c6b3b57c3c3e70e9aedc8f57cc4be40a"
    source = "https://download.visualstudio.microsoft.com/download/pr/e2e14e82-11e6-430b-a1a1-b905ab23136c/35a5e31bee5151deb0532535b6a585e8/aspnetcore-runtime-5.0.2-linux-x64.tar.gz"
    source_sha256 = "c557b6a23f2dae3baa45876e9136ce5b64cb3aa326af14494dbc7e523283fd43"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.2_linux_x64_any-stack_d94d4349.tar.xz"
    version = "5.0.2"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "87f94ac6848cc3a5df1c105a849cf513174e1e2da8f3492b8a893a64e6e041ef"
    source = "https://download.visualstudio.microsoft.com/download/pr/86b1cadb-8736-40c5-aaf8-654da39394fc/df326f9481f4da03c7e31263d42a3b1d/aspnetcore-runtime-5.0.3-linux-x64.tar.gz"
    source_sha256 = "c220edde6058fd749fb22cfe7bb432378659c2941f60f0a9865998767d63e95d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.3_linux_x64_any-stack_87f94ac6.tar.xz"
    version = "5.0.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
