api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "7f625819733e3c9557e735b75a94b39b3be34326cf8ced54aba5056115056539"
    source = "https://download.visualstudio.microsoft.com/download/pr/e91b0359-e19a-4d8d-9034-135312eec3e6/65ffbc85a45cbbd355c033b52bf4234d/aspnetcore-runtime-2.1.24-linux-x64.tar.gz"
    source_sha256 = "f445cd2a215927437c1d6c65508763674e0f74a181722e227fb719030eeec3b7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.24_linux_x64_any-stack_7f625819.tar.xz"
    version = "2.1.24"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "8082787c5ccaea684953e7b7b7435b86a03a143609164c52b9dbf1cb772ea35c"
    source = "https://download.visualstudio.microsoft.com/download/pr/3b8d8ee1-0670-46d5-ae77-e824e716993e/cb4a0f5d98ff86578ee0cb95f6e34c8f/aspnetcore-runtime-2.1.25-linux-x64.tar.gz"
    source_sha256 = "04823ee559119e502d30f0a005aa7c1846136c0b64898bfe90adebb695a38c7f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.25_linux_x64_any-stack_8082787c.tar.xz"
    version = "2.1.25"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "266c2cffb5263bfcb3ef6d5e25c2fe5e2969fe219958ef7a885e7b8c4abdddcd"
    source = "https://download.visualstudio.microsoft.com/download/pr/eca743d3-030f-4b1b-bd15-3573091f1c02/f3e464abc31deb7bc2747ed6cc1a8f5c/aspnetcore-runtime-3.1.10-linux-x64.tar.gz"
    source_sha256 = "b58376e76c68f03e142ac9a771b782cb7be926a16e920d83c711903b82608f3a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.10_linux_x64_any-stack_266c2cff.tar.xz"
    version = "3.1.10"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "e14a49fdba8492230794860e5276c2d6405a1548832565785fad5d764317531c"
    source = "https://download.visualstudio.microsoft.com/download/pr/91e7ea86-985e-401f-b3ed-103fb0fe6058/c1b1f633c9465c630e828f7f8bdf8f4e/aspnetcore-runtime-3.1.11-linux-x64.tar.gz"
    source_sha256 = "628dffa95fd8a4ac1a3f13457196b7721873288ed673c085da55daa2fb45e828"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.11_linux_x64_any-stack_e14a49fd.tar.xz"
    version = "3.1.11"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "d94d4349407cec87de9b6044f7f13d71c6b3b57c3c3e70e9aedc8f57cc4be40a"
    source = "https://download.visualstudio.microsoft.com/download/pr/e2e14e82-11e6-430b-a1a1-b905ab23136c/35a5e31bee5151deb0532535b6a585e8/aspnetcore-runtime-5.0.2-linux-x64.tar.gz"
    source_sha256 = "c557b6a23f2dae3baa45876e9136ce5b64cb3aa326af14494dbc7e523283fd43"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.2_linux_x64_any-stack_d94d4349.tar.xz"
    version = "5.0.2"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "87f94ac6848cc3a5df1c105a849cf513174e1e2da8f3492b8a893a64e6e041ef"
    source = "https://download.visualstudio.microsoft.com/download/pr/86b1cadb-8736-40c5-aaf8-654da39394fc/df326f9481f4da03c7e31263d42a3b1d/aspnetcore-runtime-5.0.3-linux-x64.tar.gz"
    source_sha256 = "c220edde6058fd749fb22cfe7bb432378659c2941f60f0a9865998767d63e95d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.3_linux_x64_any-stack_87f94ac6.tar.xz"
    version = "5.0.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
