api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "8082787c5ccaea684953e7b7b7435b86a03a143609164c52b9dbf1cb772ea35c"
    source = "https://download.visualstudio.microsoft.com/download/pr/3b8d8ee1-0670-46d5-ae77-e824e716993e/cb4a0f5d98ff86578ee0cb95f6e34c8f/aspnetcore-runtime-2.1.25-linux-x64.tar.gz"
    source_sha256 = "04823ee559119e502d30f0a005aa7c1846136c0b64898bfe90adebb695a38c7f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.25_linux_x64_any-stack_8082787c.tar.xz"
    version = "2.1.25"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "6ff9d97f61bb6f50964734851efb0b74301a31dc68e46e77498328e1b80c2503"
    source = "https://download.visualstudio.microsoft.com/download/pr/29ba76e1-db96-4cbb-8964-0a6c859712c4/d6e56c1dacf78b6846464a77dda4115d/aspnetcore-runtime-2.1.26-linux-x64.tar.gz"
    source_sha256 = "72e08cd2a26d2ce26bb0c61390feaf0781fadf60fa70d9edf56a2049b0f1e77d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.26_linux_x64_any-stack_6ff9d97f.tar.xz"
    version = "2.1.26"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "2c87b3228b7cce88a6ceefd5a2a98ace1243eeddc5efd41d58846ec6326bacee"
    source = "https://download.visualstudio.microsoft.com/download/pr/a11a4be1-2a51-4ddc-a23a-56348ea45101/20085ae5fbefd18642babcee279a74e4/aspnetcore-runtime-3.1.13-linux-x64.tar.gz"
    source_sha256 = "0d6f25f0d05972265e05b483284f968c339c1bd03500028209d32c3f618618b4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.13_linux_x64_any-stack_2c87b322.tar.xz"
    version = "3.1.13"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "b632c78673f2a408381741dfe660aed75535e2c3c473e209b3cc33f9e5e99948"
    source = "https://download.visualstudio.microsoft.com/download/pr/516b337a-83f9-4946-b2a6-b2f686e09a76/d0e82549e890c5d852c461319ffd5b31/aspnetcore-runtime-3.1.14-linux-x64.tar.gz"
    source_sha256 = "96a66d44b6aaf71da50a6709912aab36f007cd974dd3766b55c67a8aab5748a8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.14_linux_x64_any-stack_b632c786.tar.xz"
    version = "3.1.14"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "3a9e6d4f4237fda1b30c8dbac0350a3dc791d4fd1f65eb07f40c3f91536b9cf4"
    source = "https://download.visualstudio.microsoft.com/download/pr/131d9f6b-0f49-474e-a7c5-33754d4e9195/52fae63c358d8e8e6211a50a64fe3dfd/aspnetcore-runtime-5.0.4-linux-x64.tar.gz"
    source_sha256 = "92e5f21f6eda68a42628ac750decf22bb9a2be95ff0131a070bbe623b8743c50"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.4_linux_x64_any-stack_3a9e6d4f.tar.xz"
    version = "5.0.4"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "268fa83192f85fae38c0768bf39040297c68f4eac4fdac9ead16ef6730d17686"
    source = "https://download.visualstudio.microsoft.com/download/pr/827b12a8-8dea-43da-92a2-2d24c4936236/d2d61b3ed4b5ba3f682de3e04fc4d243/aspnetcore-runtime-5.0.5-linux-x64.tar.gz"
    source_sha256 = "a6db0176d2a8453bdfcb7da6e6d57300a7000eceffbaec74965ef98aacd8b316"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.5_linux_x64_any-stack_268fa831.tar.xz"
    version = "5.0.5"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
