api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "c3650d3646c13e79c2102b2a9487f02cbca61318c0fc03122676a8d322e2f016"
    source = "https://download.visualstudio.microsoft.com/download/pr/c66dd1cb-a5fc-4427-bef4-d55a1da5a5c7/17f733c7b6afe91ef9c91e9f6e170cad/aspnetcore-runtime-2.1.27-linux-x64.tar.gz"
    source_sha256 = "1863027b81a24de56ca2c2a77b96e337606b5fe0d78021e69e19bfde96e2da0a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.27_linux_x64_any-stack_c3650d36.tar.xz"
    version = "2.1.27"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "128e76c17cd73d7f382d9cd6261dddb594cd43f3719c4cfef51df8e844965eae"
    source = "https://download.visualstudio.microsoft.com/download/pr/66483281-5453-4504-9686-f72d1fd357f7/0de98386ca1709bde2b5f2f7df4c80da/aspnetcore-runtime-2.1.28-linux-x64.tar.gz"
    source_sha256 = "573bd4c0af11adfc97e84f7ba2f5045b8263e6608cad1464f8cae6f9975643e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.28_linux_x64_any-stack_128e76c1.tar.xz"
    version = "2.1.28"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "b632c78673f2a408381741dfe660aed75535e2c3c473e209b3cc33f9e5e99948"
    source = "https://download.visualstudio.microsoft.com/download/pr/516b337a-83f9-4946-b2a6-b2f686e09a76/d0e82549e890c5d852c461319ffd5b31/aspnetcore-runtime-3.1.14-linux-x64.tar.gz"
    source_sha256 = "96a66d44b6aaf71da50a6709912aab36f007cd974dd3766b55c67a8aab5748a8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.14_linux_x64_any-stack_b632c786.tar.xz"
    version = "3.1.14"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "583281c659d70f08168a82f98b22d0c1f34aff88e51fd2cd1e5945b528cd86ed"
    source = "https://download.visualstudio.microsoft.com/download/pr/8aaf94dc-ce57-4d00-9d2d-70e8b760619e/2979ffe47a37c1aa5d931ee1953613f3/aspnetcore-runtime-3.1.15-linux-x64.tar.gz"
    source_sha256 = "5e10cf25ff900aeac5b4d56eda6388ef95bbd1f5085504fd435b99e7118de94e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.15_linux_x64_any-stack_583281c6.tar.xz"
    version = "3.1.15"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "268fa83192f85fae38c0768bf39040297c68f4eac4fdac9ead16ef6730d17686"
    source = "https://download.visualstudio.microsoft.com/download/pr/827b12a8-8dea-43da-92a2-2d24c4936236/d2d61b3ed4b5ba3f682de3e04fc4d243/aspnetcore-runtime-5.0.5-linux-x64.tar.gz"
    source_sha256 = "a6db0176d2a8453bdfcb7da6e6d57300a7000eceffbaec74965ef98aacd8b316"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.5_linux_x64_any-stack_268fa831.tar.xz"
    version = "5.0.5"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "12f3bd6b62bfd1ce96a8cfcf76cab30f69386f16bc0c9e64aa23db76b34821f9"
    source = "https://download.visualstudio.microsoft.com/download/pr/4a7f1f6c-6777-42c4-9793-581bba4b632e/e03e6237a8f49f60014d459f0f758923/aspnetcore-runtime-5.0.6-linux-x64.tar.gz"
    source_sha256 = "9ab1493fb64ebe485e8d61e2010d3b46c7ee03aa8e2414931795100eb6086171"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.6_linux_x64_any-stack_12f3bd6b.tar.xz"
    version = "5.0.6"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
