api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "ASPNetCore Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "8df52beaa83510545f5598f58312bbcf65eea24055c2bef000419caa10fe3534"
    source = "https://download.visualstudio.microsoft.com/download/pr/5e23ff62-5ddd-4fc5-9f72-e4250110cf58/956138123fcefedca324b0fea6c23d15/aspnetcore-runtime-2.1.18-linux-x64.tar.gz"
    source_sha256 = "8f3a6092b26dae5c27318975c4d89297d64425424809a6c36c984f02723475a1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.18_linux_x64_any-stack_8df52bea.tar.xz"
    version = "2.1.18"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "88b4f28b3df8d954d5e06c94e8eb345f0e8dbfe77bd56a5c9c8cb350e065e71a"
    source = "https://download.visualstudio.microsoft.com/download/pr/abf8cad9-fe36-4bb6-9cdb-926a50bf63c6/5dc2f4e3e133ef073f12340d4fd6e943/aspnetcore-runtime-2.1.19-linux-x64.tar.gz"
    source_sha256 = "ee93178335ab356a289c25c411354bef70b5a5bdcb9462c419011210e391e8f3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.19_linux_x64_any-stack_88b4f28b.tar.xz"
    version = "2.1.19"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "c96379e0d05c14e5f790bc806e101dbe49879c7b3df52849493a5831d66f5977"
    source = "https://download.visualstudio.microsoft.com/download/pr/7faca87b-7526-4dcd-ae23-4559d2c51ce3/7db1f314c733191ea43e1757e3b2583d/aspnetcore-runtime-3.1.3-linux-x64.tar.gz"
    source_sha256 = "34cc5c7f16b45234603d9f352a1bd3997d5e07d7380c49266860f75dbc29146d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.3_linux_x64_any-stack_c96379e0.tar.xz"
    version = "3.1.3"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "876b3b1add3748481b419037b5267e70466adc722ca1f7f566cd7fd7bf6145d4"
    source = "https://download.visualstudio.microsoft.com/download/pr/a1ddc998-933c-47af-b8c7-dc2503e44e91/42d8cd08b2055df52c9457c993911f2e/aspnetcore-runtime-3.1.4-linux-x64.tar.gz"
    source_sha256 = "ca41ea778e93449c1b37dea3e50850ce170c3737fe367a39d02eb786d6fdf97e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.4_linux_x64_any-stack_876b3b1a.tar.xz"
    version = "3.1.4"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
